// Auto-generated by `npx supabase gen types` — regenerate after schema changes.
// Hand-crafted initial version; run the gen command once local DB is running.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Region = 'north' | 'haifa' | 'sharon' | 'center' | 'jerusalem' | 'shfela' | 'south'
export type UserRole = 'viewer' | 'contributor' | 'moderator'
export type CutCategory = 'beef' | 'lamb' | 'fish'
export type CutPrimal = 'chuck' | 'rib' | 'brisket' | 'loin' | 'round' | 'plate' | 'flank' | 'shank' | 'other'
export type CutStatus = 'active' | 'merged' | 'pending'
export type VendorType = 'chain' | 'butcher' | 'online' | 'market' | 'farm'
export type VendorStatus = 'pending' | 'active' | 'closed' | 'merged'
export type ObservationSource = 'manual' | 'photo' | 'web_auto'
export type ObservationStatus = 'active' | 'hidden' | 'removed'
export type AliasLang = 'he' | 'en' | 'mixed'
export type VendorSourceKind = 'price_page' | 'weekly_ad' | 'social'
export type VendorSourceStatus = 'active' | 'broken' | 'paused'
export type IngestionResult = 'ok' | 'parse_error' | 'fetch_error'

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string
          role: UserRole
          home_region: Region | null
          home_lat: number | null
          home_lng: number | null
          created_at: string
        }
        Insert: {
          id: string
          display_name: string
          role?: UserRole
          home_region?: Region | null
          home_lat?: number | null
          home_lng?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          display_name?: string
          role?: UserRole
          home_region?: Region | null
          home_lat?: number | null
          home_lng?: number | null
          created_at?: string
        }
        Relationships: [{ foreignKeyName: 'profiles_id_fkey'; columns: ['id']; referencedRelation: 'users'; referencedColumns: ['id'] }]
      }
      cuts: {
        Row: {
          id: string
          category: CutCategory
          name_en: string
          name_he: string
          israeli_number: number | null
          primal: CutPrimal | null
          kosher_notes: string | null
          created_by: string | null
          status: CutStatus
          created_at: string
        }
        Insert: {
          id?: string
          category?: CutCategory
          name_en: string
          name_he: string
          israeli_number?: number | null
          primal?: CutPrimal | null
          kosher_notes?: string | null
          created_by?: string | null
          status?: CutStatus
          created_at?: string
        }
        Update: {
          id?: string
          category?: CutCategory
          name_en?: string
          name_he?: string
          israeli_number?: number | null
          primal?: CutPrimal | null
          kosher_notes?: string | null
          created_by?: string | null
          status?: CutStatus
          created_at?: string
        }
        Relationships: []
      }
      cut_aliases: {
        Row: {
          id: string
          cut_id: string
          alias: string
          lang: AliasLang
          created_at: string
        }
        Insert: {
          id?: string
          cut_id: string
          alias: string
          lang: AliasLang
          created_at?: string
        }
        Update: {
          id?: string
          cut_id?: string
          alias?: string
          lang?: AliasLang
          created_at?: string
        }
        Relationships: [{ foreignKeyName: 'cut_aliases_cut_id_fkey'; columns: ['cut_id']; referencedRelation: 'cuts'; referencedColumns: ['id'] }]
      }
      alias_suggestions: {
        Row: {
          id: string
          cut_id: string
          suggested_alias: string
          suggested_by: string
          created_at: string
          promoted_at: string | null
          promoted_by: string | null
        }
        Insert: {
          id?: string
          cut_id: string
          suggested_alias: string
          suggested_by: string
          created_at?: string
          promoted_at?: string | null
          promoted_by?: string | null
        }
        Update: {
          id?: string
          cut_id?: string
          suggested_alias?: string
          suggested_by?: string
          created_at?: string
          promoted_at?: string | null
          promoted_by?: string | null
        }
        Relationships: []
      }
      vendors: {
        Row: {
          id: string
          name: string
          type: VendorType
          region: Region
          city: string
          address: string | null
          lat: number | null
          lng: number | null
          phone: string | null
          website: string | null
          delivers: boolean
          delivery_regions: string[] | null
          delivery_fee: number | null
          delivery_min_order: number | null
          rating: number | null
          status: VendorStatus
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          type: VendorType
          region: Region
          city: string
          address?: string | null
          lat?: number | null
          lng?: number | null
          phone?: string | null
          website?: string | null
          delivers?: boolean
          delivery_regions?: string[] | null
          delivery_fee?: number | null
          delivery_min_order?: number | null
          rating?: number | null
          status?: VendorStatus
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          type?: VendorType
          region?: Region
          city?: string
          address?: string | null
          lat?: number | null
          lng?: number | null
          phone?: string | null
          website?: string | null
          delivers?: boolean
          delivery_regions?: string[] | null
          delivery_fee?: number | null
          delivery_min_order?: number | null
          rating?: number | null
          status?: VendorStatus
          created_by?: string | null
          created_at?: string
        }
        Relationships: []
      }
      photos: {
        Row: {
          id: string
          storage_path: string
          vendor_id: string
          uploaded_by: string
          extraction_json: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          storage_path: string
          vendor_id: string
          uploaded_by: string
          extraction_json?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          storage_path?: string
          vendor_id?: string
          uploaded_by?: string
          extraction_json?: Json | null
          created_at?: string
        }
        Relationships: []
      }
      price_observations: {
        Row: {
          id: string
          vendor_id: string
          cut_id: string
          price_per_kg: number
          currency: string
          is_sale: boolean
          sale_ends_at: string | null
          source: ObservationSource
          confidence: number | null
          photo_id: string | null
          source_url: string | null
          contributor_id: string | null
          observed_at: string
          created_at: string
          last_seen_at: string
          status: ObservationStatus
          raw_text: string | null
        }
        Insert: {
          id?: string
          vendor_id: string
          cut_id: string
          price_per_kg: number
          currency?: string
          is_sale?: boolean
          sale_ends_at?: string | null
          source: ObservationSource
          confidence?: number | null
          photo_id?: string | null
          source_url?: string | null
          contributor_id?: string | null
          observed_at: string
          created_at?: string
          last_seen_at?: string
          status?: ObservationStatus
          raw_text?: string | null
        }
        Update: {
          id?: string
          vendor_id?: string
          cut_id?: string
          price_per_kg?: number
          currency?: string
          is_sale?: boolean
          sale_ends_at?: string | null
          source?: ObservationSource
          confidence?: number | null
          photo_id?: string | null
          source_url?: string | null
          contributor_id?: string | null
          observed_at?: string
          created_at?: string
          last_seen_at?: string
          status?: ObservationStatus
          raw_text?: string | null
        }
        Relationships: []
      }
      vendor_sources: {
        Row: {
          id: string
          vendor_id: string
          url: string
          kind: VendorSourceKind
          crawl_frequency: string
          status: VendorSourceStatus
          last_run_at: string | null
          fail_count: number
          created_at: string
        }
        Insert: {
          id?: string
          vendor_id: string
          url: string
          kind: VendorSourceKind
          crawl_frequency?: string
          status?: VendorSourceStatus
          last_run_at?: string | null
          fail_count?: number
          created_at?: string
        }
        Update: {
          id?: string
          vendor_id?: string
          url?: string
          kind?: VendorSourceKind
          crawl_frequency?: string
          status?: VendorSourceStatus
          last_run_at?: string | null
          fail_count?: number
          created_at?: string
        }
        Relationships: []
      }
      ingestion_runs: {
        Row: {
          id: string
          source_id: string
          started_at: string
          finished_at: string | null
          result: IngestionResult | null
          observations_written: number
          queued_for_review: number
          log: Json | null
        }
        Insert: {
          id?: string
          source_id: string
          started_at: string
          finished_at?: string | null
          result?: IngestionResult | null
          observations_written?: number
          queued_for_review?: number
          log?: Json | null
        }
        Update: {
          id?: string
          source_id?: string
          started_at?: string
          finished_at?: string | null
          result?: IngestionResult | null
          observations_written?: number
          queued_for_review?: number
          log?: Json | null
        }
        Relationships: []
      }
      shopping_lists: {
        Row: {
          id: string
          owner_id: string
          name: string
          items: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          name: string
          items?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          owner_id?: string
          name?: string
          items?: Json
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      flags: {
        Row: {
          id: string
          observation_id: string
          flagged_by: string
          reason: string
          created_at: string
          resolved_by: string | null
          resolved_at: string | null
          resolution: string | null
        }
        Insert: {
          id?: string
          observation_id: string
          flagged_by: string
          reason: string
          created_at?: string
          resolved_by?: string | null
          resolved_at?: string | null
          resolution?: string | null
        }
        Update: {
          id?: string
          observation_id?: string
          flagged_by?: string
          reason?: string
          created_at?: string
          resolved_by?: string | null
          resolved_at?: string | null
          resolution?: string | null
        }
        Relationships: []
      }
      invites: {
        Row: {
          id: string
          code: string
          created_by: string
          used_by: string | null
          expires_at: string
          used_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          code: string
          created_by: string
          used_by?: string | null
          expires_at: string
          used_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          code?: string
          created_by?: string
          used_by?: string | null
          expires_at?: string
          used_at?: string | null
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<never, never>
    Functions: {
      get_user_role: { Args: Record<PropertyKey, never>; Returns: string }
      // NOTE: manually added — do not overwrite when running gen types
      validate_invite_code: { Args: { p_code: string }; Returns: boolean }
      get_vendors_in_radius: {
        Args: { user_lat: number; user_lng: number; radius_km: number }
        Returns: Database['public']['Tables']['vendors']['Row'][]
      }
      is_moderator: { Args: Record<PropertyKey, never>; Returns: boolean }
      normalize_alias_input: { Args: { raw: string }; Returns: string }
      resolve_cut_alias: {
        Args: { raw: string }
        Returns: { cut_id: string; match_type: string; sim: number }[]
      }
      cut_regional_median: {
        Args: { p_cut_id: string; p_region: string; p_days?: number }
        Returns: number
      }
      observation_freshness: {
        Args: { p_source: string; p_observed_at: string; p_is_sale?: boolean; p_sale_ends_at?: string | null }
        Returns: string
      }
    }
    Enums: Record<never, never>
    CompositeTypes: Record<never, never>
  }
}

// Convenience helpers
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
